name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy via SFTP/FTPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Upload to Hosting via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6 
        with:
          server: ftp://195.35.54.46
          username: u996263040.v2.moesneeds.id
          password: ${{ secrets.FTP_PASS }}
          protocol: ftps
          port: 21
          local-dir: ./        # folder lokal yang mau diupload
          server-dir: /public_html/ # folder di hosting
          timeout: 600